version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpcrm

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: rp_crm_app
    restart: always

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - db

volumes:
  postgres_data:
